# Generated by Django 4.1.7 on 2023-05-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feednews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("price", models.IntegerField()),
                ("pages", models.IntegerField()),
                ("author", models.CharField(default="", max_length=255)),
                ("year", models.CharField(default="", max_length=255)),
                ("comment", models.CharField(default="", max_length=255)),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
    ]
