# Generated by Django 4.1.7 on 2023-03-31 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feednews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='image_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='feednews.images'),
        ),
    ]
