# Generated by Django 4.1.7 on 2023-05-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("feednews", "0002_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="images_table",
                to="feednews.images",
            ),
        ),
    ]
